name: Build and Push Image
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-and-push-image:
    runs-on: portkey-runner
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create image tag
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.REPOSITORY_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY }}/portkey-login-page # change this to your project frontend name
          tags: |
            type=ref,event=tag
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          NEXT_PUBLIC_APP_APPLE_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_APP_APPLE_REDIRECT_URI }}
          NEXT_PUBLIC_APP_MAINNET_SERVICE: ${{ secrets.NEXT_PUBLIC_APP_MAINNET_SERVICE }}
          NEXT_PUBLIC_APP_TESTNET_SERVICE: ${{ secrets.NEXT_PUBLIC_APP_TESTNET_SERVICE }}
          NEXT_PUBLIC_APP_MAINNET_CONNECT: ${{ secrets.NEXT_PUBLIC_APP_MAINNET_CONNECT }}
          NEXT_PUBLIC_APP_TESTNET_CONNECT: ${{ secrets.NEXT_PUBLIC_APP_TESTNET_CONNECT }}
          NEXT_PUBLIC_APP_MAINNET_GRAPHQL: ${{ secrets.NEXT_PUBLIC_APP_MAINNET_GRAPHQL }}
          NEXT_PUBLIC_APP_TESTNET_GRAPHQL: ${{ secrets.NEXT_PUBLIC_APP_TESTNET_GRAPHQL }}
          NEXT_PUBLIC_APP_APPLE_REDIRECT_URI_V2: ${{ secrets.NEXT_PUBLIC_APP_APPLE_REDIRECT_URI_V2 }}
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NEXT_PUBLIC_APP_APPLE_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_APP_APPLE_REDIRECT_URI }}
            NEXT_PUBLIC_APP_MAINNET_SERVICE: ${{ secrets.NEXT_PUBLIC_APP_MAINNET_SERVICE }}
            NEXT_PUBLIC_APP_TESTNET_SERVICE: ${{ secrets.NEXT_PUBLIC_APP_TESTNET_SERVICE }}
            NEXT_PUBLIC_APP_MAINNET_CONNECT: ${{ secrets.NEXT_PUBLIC_APP_MAINNET_CONNECT }}
            NEXT_PUBLIC_APP_TESTNET_CONNECT: ${{ secrets.NEXT_PUBLIC_APP_TESTNET_CONNECT }}
            NEXT_PUBLIC_APP_MAINNET_GRAPHQL: ${{ secrets.NEXT_PUBLIC_APP_MAINNET_GRAPHQL }}
            NEXT_PUBLIC_APP_TESTNET_GRAPHQL: ${{ secrets.NEXT_PUBLIC_APP_TESTNET_GRAPHQL }}
            NEXT_PUBLIC_APP_APPLE_REDIRECT_URI_V2: ${{ secrets.NEXT_PUBLIC_APP_APPLE_REDIRECT_URI_V2 }}
